trigger:
- master

pool:
  # vmImage: ubuntu-latest
  name: Dev

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'hello/pom.xml'
    goals: 'clean package'
    options: '-Dtest="HelloRepositoryTest"'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: which 'dotnet'
  displayName: 'Run a one-line script'
